name: ghosts
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - matplotlib
  - numpy
  - scipy
  - pandas
  - openpyxl
  - pyyaml
  - jupyter
  - sphinx
  - sphinx_rtd_theme
  - seaborn
